image: Visual Studio 2017
version: build{build}

build_script:
- cmd: "ECHO TAG: %APPVEYOR_REPO_TAG_NAME%"
- cmd: "ECHO PR: %APPVEYOR_PULL_REQUEST_NUMBER%"
- cmd: "ECHO BUILD: %APPVEYOR_BUILD_NUMBER%"
- ps: >-
    . ./build.ps1

    Invoke-Build -ProjectPath "$env:APPVEYOR_BUILD_FOLDER/src/Iamport.RestApi" -Tag "$env:APPVEYOR_REPO_TAG_NAME" -PRNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -BuildNumber "$env:APPVEYOR_BUILD_NUMBER"
test_script:
- cmd: cd test/Iamport.RestApi.Tests
- cmd: dotnet test
- cmd: cd ../..

artifacts:
- path: '**\*.nupkg'
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: OdlepcT+ry0jb8FB3n6AQV23YA5/TtBC572OTrE/oLiKuMu807Re9Pqo78fYXbNI
  on:
    appveyor_repo_tag: true

skip_commits:
  message: /((Update|Create) .*\.(md|png|jpg|jpeg|bmp|gif))|(Create|Update) appveyor.yml/
